"use client";

import { createContext, useContext, useState, useEffect } from 'react'

type Language = 'tr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  tr: {
    // Header
    'header.announcement': '📢 7 GÜN ÜCRETSİZ DENEYİN - Kredi kartı gerekmez! | Özel lansman indirimi: %20 tasarruf',
    'nav.features': 'Özellikler',
    'nav.howItWorks': 'Nasıl Çalışır?',
    'nav.pricing': 'Fiyatlandırma',
    'nav.adminPanel': 'Admin Panel',
    'nav.tryFree': '7 Gün Ücretsiz Dene',
    
    // Hero Section
    'hero.badge.new': 'Yeni',
    'hero.badge.trustedBy': '500+ berber tarafından tercih ediliyor',
    'hero.title': 'WhatsApp Üzerinden',
    'hero.titleHighlight': '7/24 Randevu Sistemi',
    'hero.subtitle': 'Kuaför ve güzellik salonları için yapay zeka destekli WhatsApp randevu asistanı. Müşterileriniz yazsın, asistanınız anında cevap versin.',
    'hero.testimonial': '"3 aydır kullanıyorum, randevularım %40 arttı ve asla bir randevuyu kaçırmıyorum!"',
    'hero.testimonialAuthor': '- Ahmet Kuaför, İstanbul',
    'hero.cta': 'Ücretsiz Deneyin',
    'hero.benefit1': '7 gün ücretsiz deneme',
    'hero.benefit2': 'Kredi kartı gerekmez',
    'hero.benefit3': 'Meta onaylı iş ortağı',
    
    // WhatsApp Demo    
    'demo.assistant': 'Kuafi Asistanı',
    'demo.online': 'Çevrimiçi',
    'demo.message1': 'Merhaba! Ben Kuafi asistanı. Size nasıl yardımcı olabilirim?',
    'demo.message2': 'Merhaba, yarın için bir saç kesimi randevusu almak istiyorum',
    'demo.message3': 'Tabii! Yarın için uygun saatlerimiz: 10:00, 14:30 ve 16:00. Hangisi size uygun?',
    
    // Features Section
    'features.title': 'Sizin İçin Kişiselleştirilmiş WhatsApp Asistanı',
    'features.subtitle': 'Her güzellik salonu için ayrı kurulum, ayrı yapılandırma',
    'features.smartAppointment.title': 'Akıllı Randevu Yönetimi',
    'features.smartAppointment.feature1': 'Otomatik randevu planlama',
    'features.smartAppointment.feature2': 'Randevu iptal/erteleme',
    'features.smartAppointment.feature3': 'Boş zaman önerileri',
    'features.smartAppointment.feature4': 'Hatırlatma mesajları',
    'features.aiAssistant.title': 'Yapay Zeka Asistanı',
    'features.aiAssistant.feature1': 'Doğal dil anlama',
    'features.aiAssistant.feature2': 'Türkçe ve İngilizce desteği',
    'features.aiAssistant.feature3': 'Akıllı öneriler',
    'features.aiAssistant.feature4': '7/24 hizmet',
    'features.security.title': 'Güvenlik ve Uyumluluk',
    'features.security.feature1': 'Meta onaylı API',
    'features.security.feature2': 'KVKK uyumlu',
    'features.security.feature3': 'SSL güvenliği',
    'features.security.feature4': 'Veri yedekleme',
    
    // Success Metrics Section
    'metrics.title': 'Başarı Metrikleri',
    'metrics.subtitle': 'Kuafi.com kullanan işletmelerin gerçek sonuçları',
    'metrics.bookingIncrease.title': 'Randevu Doluluk Artışı',
    'metrics.bookingIncrease.description': 'Boş randevu saatleri azalır, iş hacminiz artar',
    'metrics.timeSaving.title': 'Telefonda Zaman Kazancı',
    'metrics.timeSaving.description': 'Telefon aramalarını cevaplayarak kaybedilen süre azalır',
    'metrics.newCustomers.title': 'Yeni Müşteri Artışı',
    'metrics.newCustomers.description': '7/24 randevu alınabilmesi yeni müşteri kazanımını artırır',
    'metrics.cancellationReduction.title': 'İptal Oranı Azalışı',
    'metrics.cancellationReduction.description': 'Otomatik hatırlatmalar sayesinde daha az randevu iptali',
    'metrics.testimonial': '"Kuafi.com ile çalışmaya başladıktan sonra telefonda geçirdiğim vakit %90 azaldı ve randevu doluluk oranim %67 arttı. Artık müşterilerime daha kaliteli hizmet verebiliyorum."',
    'metrics.testimonialAuthor': 'Ahmet Kuaför',
    'metrics.testimonialLocation': 'İstanbul, Kadıköy',
    
    // How It Works Section
    'howItWorks.title': 'Nasıl Çalışır?',
    'howItWorks.subtitle': '3 Adımda Basit',
    'howItWorks.step1.title': 'Müşteri Yazıyor',
    'howItWorks.step1.description': 'Müşterileriniz WhatsApp üzerinden size kolayca ulaşır.',
    'howItWorks.step2.title': 'Bot Cevaplıyor',
    'howItWorks.step2.description': 'AI destekli asistan randevuları otomatik oluşturur.',
    'howItWorks.step3.title': 'Takvime İşleniyor',
    'howItWorks.step3.description': 'Randevu otomatik olarak takviminize eklenir.',
    
    // Pricing Section
    'pricing.title': 'Fiyatlandırma Planları',
    'pricing.subtitle': 'İşletmenize en uygun planı seçin',
    'pricing.comparison.title': 'Özellik Karşılaştırması',
    'pricing.comparison.features': 'Özellikler',
    'pricing.comparison.competitor1': 'Rakip X',
    'pricing.comparison.competitor2': 'Rakip Y',
    'pricing.comparison.whatsappApi': 'WhatsApp API',
    'pricing.comparison.turkishSupport': 'Türkçe Dil Desteği',
    'pricing.comparison.calendarIntegration': 'Takvim Entegrasyonları',
    'pricing.comparison.support247': '7/24 Türkçe Destek',
    'pricing.comparison.adminPanel': 'Gelişmiş Admin Panel',
    'pricing.freePlan.title': '🎉 Ücretsiz Plan',
    'pricing.freePlan.description': 'Başlangıç için ideal',
    'pricing.freePlan.cta': 'Başla',
    'pricing.freePlan.feature1': '30 günlük deneme',
    'pricing.freePlan.feature2': '100 mesaj / ay',
    'pricing.freePlan.feature3': 'Email desteği',
    'pricing.standardPlan.title': '💼 Standart Plan',
    'pricing.standardPlan.description': 'Küçük ve orta işletmeler için',
    'pricing.standardPlan.recommended': 'ÖNERİLEN',
    'pricing.standardPlan.discount': '%20 indirim - sınırlı süre!',
    'pricing.standardPlan.cta': 'Hemen Başla',
    'pricing.standardPlan.feature1': 'Sınırsız mesaj',
    'pricing.standardPlan.feature2': 'Özel takvim entegrasyonu',
    'pricing.standardPlan.feature3': 'Marka özelleştirmeleri',
    'pricing.standardPlan.feature4': 'WhatsApp desteği',
    'pricing.standardPlan.feature5': 'Temel admin panel özellikleri',
    'pricing.standardPlan.note': 'WhatsApp mesaj maliyetleri ($0.0055/mesaj) sizin tarafınızdan karşılanır. Detaylı bilgi için tıklayın.',
    'pricing.premiumPlan.title': '👑 Premium Plan',
    'pricing.premiumPlan.description': 'Büyük işletmeler ve zincirler için',
    'pricing.premiumPlan.discount': '%20 indirim - sınırlı süre!',
    'pricing.premiumPlan.cta': 'İletişime Geç',
    'pricing.premiumPlan.feature1': 'Tüm özellikler +',
    'pricing.premiumPlan.feature2': 'WhatsApp Business API kurulumu',
    'pricing.premiumPlan.feature3': '7/24 destek',
    'pricing.premiumPlan.feature4': 'Öncelikli destek',
    'pricing.premiumPlan.feature5': 'İlk 1000 mesaj bizden! (Değer: $50)',
    'pricing.premiumPlan.feature6': 'Gelişmiş admin panel özellikleri',
    'pricing.premiumPlan.note': 'Premium pakette WhatsApp mesaj maliyetleri bizim tarafımızdan karşılanır.',
    'pricing.whatsappCosts.title': 'WhatsApp Mesaj Ücretleri Hakkında',
    'pricing.whatsappCosts.description': 'WhatsApp mesaj ücretleri sizden gizlenmez! WhatsApp Business API kullanımı için Meta tarafından her mesaj başına ücret alınmaktadır.',
    'pricing.whatsappCosts.standard': 'Standart Pakette',
    'pricing.whatsappCosts.standardNote': 'WhatsApp mesaj maliyetleri ($0.0055/mesaj) sizin tarafınızdan karşılanır.',
    'pricing.whatsappCosts.premium': 'Premium Pakette',
    'pricing.whatsappCosts.premiumNote': 'WhatsApp mesaj maliyetleri tarafımızdan karşılanır + ilk 1000 mesaj bizden!',
    
    // Final CTA Section
    'finalCta.title': 'İşletmenize WhatsApp Asistanı Eklemek İçin Hazır mısınız?',
    'finalCta.subtitle': 'Daha az iş, daha çok randevu. Müşterilerinize 7/24 yanıt veren asistanınız ile işinizi büyütün.',
    'finalCta.cta': '7 Gün Ücretsiz Deneyin',
    
    // FAQ Section
    'faq.title': 'Sık Sorulan Sorular',
    'faq.subtitle': 'Merak ettiğiniz soruların cevapları',
    'faq.q1.question': 'WhatsApp API zor mu kurulur?',
    'faq.q1.answer': 'Hayır, Kuafi ile WhatsApp API kurulumu tamamen bizim tarafımızdan yapılır. Premium paketimizde WhatsApp Business API kurulumu ve entegrasyonu dahildir.',
    'faq.q2.question': 'Deneme süresi ne kadar?',
    'faq.q2.answer': 'Tüm özelliklerimizi 7 gün boyunca ücretsiz deneyebilirsiniz. Deneme süresinde herhangi bir kredi kartı bilgisi istenmez.',
    'faq.q3.question': 'Bot Türkçe mi?',
    'faq.q3.answer': 'Evet, botumuz %100 Türkçe destekli olup, Türkçe dil anlama ve işleme yeteneklerine sahiptir.',
    'faq.q4.question': 'Takvim neye entegre oluyor?',
    'faq.q4.answer': 'Şu anda Google Takvim, Microsoft Outlook ve Apple Takvim entegrasyonlarını destekliyoruz. Ayrıca özel takvim sistemlerinize de entegrasyon sağlayabiliyoruz.',
    'faq.q5.question': 'Eski randevularım ne oluyor?',
    'faq.q5.answer': 'Mevcut takvim sisteminizdeki tüm randevular korunur. Kuafi, mevcut randevularınıza saygı gösterecek şekilde çalışır.',
    
    // Admin Features Section
    'adminFeatures.badge': 'YENİ',
    'adminFeatures.title': 'Gelişmiş Yönetim Paneli',
    'adminFeatures.subtitle': 'İşletmenizi tek noktadan yönetebileceğiniz güçlü admin paneliyle tanışın',
    'adminFeatures.appointmentManagement.title': 'Randevu Yönetimi',
    'adminFeatures.appointmentManagement.description': 'Tüm randevularınızı görüntüleyin, düzenleyin ve iptal edin. Boş saatleri ve yoğun günleri kolayca takip edin.',
    'adminFeatures.customerDatabase.title': 'Müşteri Veritabanı',
    'adminFeatures.customerDatabase.description': 'Müşteri bilgilerinizi tek bir yerden yönetin. Randevu geçmişi, tercihler ve iletişim bilgilerini kolayca erişin.',
    'adminFeatures.analytics.title': 'Analitik ve Raporlar',
    'adminFeatures.analytics.description': 'İşletmenizin performansını ölçün. Doluluk oranları, iptal istatistikleri ve gelir raporlarına erişin.',
    'adminFeatures.customizable.title': 'Özelleştirilebilir Kontrol Paneli',
    'adminFeatures.customizable.description': 'Yönetim panelinizi ihtiyaçlarınıza göre özelleştirin. Sizin için önemli olan metrikleri ön plana çıkarın.',
    'adminFeatures.customizable.feature1': 'Günlük, haftalık ve aylık randevu görünümleri',
    'adminFeatures.customizable.feature2': 'WhatsApp mesajlaşma geçmişi ve istatistikleri',
    'adminFeatures.customizable.feature3': 'Özelleştirilebilir otomatik mesaj şablonları',
    'adminFeatures.customizable.feature4': 'Detaylı finansal raporlar ve tahminler',
    'adminFeatures.customizable.cta': 'Daha Fazla Bilgi',
    'adminFeatures.mobile.title': 'Mobil Erişim',
    'adminFeatures.mobile.description': 'Admin panelinize dilediğiniz yerden, dilediğiniz cihazdan erişin. Tamamen mobil uyumlu arayüz sayesinde yolda bile işletmenizi yönetin.',
    'adminFeatures.mobile.badge': '%100 Mobil Uyumlu',
    'adminFeatures.mobile.subtitle': 'Tüm cihazlarda mükemmel deneyim',
    'adminFeatures.multiUser.title': 'Çoklu Kullanıcı Desteği',
    'adminFeatures.multiUser.description': 'Ekibinizin farklı üyelerine özel izinler tanımlayın. Kimin neyi görebileceğini ve düzenleyebileceğini siz belirleyin.',
    'adminFeatures.multiUser.roleAccess': 'Rol Bazlı Erişim',
    'adminFeatures.multiUser.roles': 'Yönetici, çalışan ve asistan rolleri',
    
    // Contact Section
    'contact.quickContact': 'Hemen İletişime Geç',
    'contact.title': 'Hızlı İletişim ve Referanslar',
    'contact.subtitle': 'Türkiye\'nin önde gelen 500+ işletmesi Kuafi.com ile randevu sistemlerini otomatikleştiriyor',
    'contact.testimonialsTitle': 'Kullanıcılarımız Ne Diyor?',
    'contact.testimonial1': '"Kuafi.com\'yi kullanmaya başladıktan sonra boş randevu saatlerim %80 azaldı. Artık telefonla uğraşmak yerine müşterilerime odaklanabiliyorum."',
    'contact.testimonial1Author': 'Ahmet Kuaför',
    'contact.testimonial1Location': 'İstanbul, Kadıköy',
    'contact.testimonial1Duration': '4 aydır kullanıyor',
    'contact.testimonial2': '"Müşterilerimiz WhatsApp üzerinden 7/24 randevu alabildiği için çok memnunlar. Özellikle hatırlatma mesajları iptal oranlarını ciddi şekilde azalttı."',
    'contact.testimonial2Author': 'Deniz Güzellik',
    'contact.testimonial2Location': 'Ankara, Çankaya',
    'contact.testimonial2Duration': '6 aydır kullanıyor',
    'contact.formTitle': 'Bizimle İletişime Geçin',
    'contact.nameLabel': 'İsim Soyisim',
    'contact.namePlaceholder': 'Adınız Soyadınız',
    'contact.phoneLabel': 'Telefon Numarası',
    'contact.phonePlaceholder': '+90 5XX XXX XX XX',
    'contact.emailLabel': 'E-posta',
    'contact.emailPlaceholder': 'ornek@domain.com',
    'contact.businessTypeLabel': 'İşletme Türü',
    'contact.businessTypePlaceholder': 'Seçiniz',
    'contact.messageLabel': 'Mesaj',
    'contact.messagePlaceholder': 'Sorularınız veya detaylar...',
    'contact.submitButton': 'Mesaj Gönder',
    'contact.privacyNote': 'Bilgileriniz KVKK kapsamında korunmaktadır.',
    'contact.privacyLink': 'Gizlilik Politikamız',
    'contact.businessOption1': 'Kuaför / Güzellik Salonu',
    'contact.businessOption2': 'SPA / Masaj Salonu',
    'contact.businessOption3': 'Diyetisyen',
    'contact.businessOption4': 'Doktor / Klinik',
    'contact.businessOption5': 'Diğer',
    
    // Pricing Section
    'pricing.title': 'Fiyatlandırma Planları',
    'pricing.subtitle': 'İşletmenize en uygun planı seçin',
    'pricing.videoTitle': 'Kuafi.com\'yi 45 saniyede keşfedin',
    'pricing.specialOffer': '⏳ Özel Teklif: %20 İndirim - Son Gün!',
    'pricing.comparison.features': 'Özellikler',
    'pricing.comparison.competitor1': 'Rakip X',
    'pricing.comparison.competitor2': 'Rakip Y',
    'pricing.comparison.whatsappApi': 'WhatsApp API',
    'pricing.comparison.turkishSupport': 'Türkçe Dil Desteği',
    'pricing.comparison.calendarIntegration': 'Takvim Entegrasyonları',
    'pricing.comparison.support247': '7/24 Türkçe Destek',
    'pricing.comparison.adminPanel': 'Gelişmiş Admin Panel',
    
    // Pricing Plans
    'pricing.freePlan.title': '🎉 Ücretsiz Plan',
    'pricing.freePlan.description': 'Başlangıç için ideal',
    'pricing.freePlan.price': '0₺',
    'pricing.freePlan.period': '/aylık',
    'pricing.freePlan.cta': 'Başla',
    'pricing.freePlan.feature1': '30 günlük deneme',
    'pricing.freePlan.feature2': '100 mesaj / ay',
    'pricing.freePlan.feature3': 'Email desteği',
    
    'pricing.standardPlan.badge': 'ÖNERİLEN',
    'pricing.standardPlan.title': '💼 Standart Plan',
    'pricing.standardPlan.description': 'Küçük ve orta işletmeler için',
    'pricing.standardPlan.originalPrice': '375₺',
    'pricing.standardPlan.price': '299₺',
    'pricing.standardPlan.period': '/aylık',
    'pricing.standardPlan.discount': '%20 indirim - sınırlı süre!',
    'pricing.standardPlan.cta': 'Hemen Başla',
    'pricing.standardPlan.feature1': 'Sınırsız mesaj',
    'pricing.standardPlan.feature2': 'Özel takvim entegrasyonu',
    'pricing.standardPlan.feature3': 'Marka özelleştirmeleri',
    'pricing.standardPlan.feature4': 'WhatsApp desteği',
    'pricing.standardPlan.feature5': 'Temel admin panel özellikleri',
    'pricing.standardPlan.note': 'WhatsApp mesaj maliyetleri ($0.0055/mesaj) sizin tarafınızdan karşılanır. Detaylı bilgi için',
    'pricing.standardPlan.clickHere': 'tıklayın',
    
    'pricing.premiumPlan.title': '👑 Premium Plan',
    'pricing.premiumPlan.description': 'Büyük işletmeler ve zincirler için',
    'pricing.premiumPlan.originalPrice': '749₺',
    'pricing.premiumPlan.price': '599₺',
    'pricing.premiumPlan.period': '/aylık',
    'pricing.premiumPlan.discount': '%20 indirim - sınırlı süre!',
    'pricing.premiumPlan.cta': 'İletişime Geç',
    'pricing.premiumPlan.feature1': 'Tüm özellikler +',
    'pricing.premiumPlan.feature2': 'WhatsApp Business API kurulumu',
    'pricing.premiumPlan.feature3': '7/24 destek',
    'pricing.premiumPlan.feature4': 'Öncelikli destek',
    'pricing.premiumPlan.feature5': 'İlk 1000 mesaj bizden! (Değer: $50)',
    'pricing.premiumPlan.feature6': 'Gelişmiş admin panel özellikleri',
    'pricing.premiumPlan.note': 'Premium pakette WhatsApp mesaj maliyetleri bizim tarafımızdan karşılanır.',
    
    'pricing.whatsappCosts.title': 'WhatsApp Mesaj Ücretleri Hakkında',
    'pricing.whatsappCosts.description': 'WhatsApp mesaj ücretleri sizden gizlenmez! WhatsApp Business API kullanımı için Meta tarafından her mesaj başına ücret alınmaktadır.',
    'pricing.whatsappCosts.standardTitle': 'Standart Pakette',
    'pricing.whatsappCosts.standardNote': 'WhatsApp mesaj maliyetleri ($0.0055/mesaj) sizin tarafınızdan karşılanır.',
    'pricing.whatsappCosts.premiumTitle': 'Premium Pakette',
    'pricing.whatsappCosts.premiumNote': 'WhatsApp mesaj maliyetleri tarafımızdan karşılanır + ilk 1000 mesaj bizden!',
    
    // Demo Section  
    'demo.title': 'Canlı Demo',
    'demo.subtitle': 'Tek tıkla botla konuşmaya başlayın ve Kuafi.com\'yi hemen deneyimleyin.',
    'demo.tryWhatsApp': 'WhatsApp\'tan Deneyin',
    'demo.getDemo': 'Demo Almak İstiyorum',
    'demo.turkishMessage1': 'Merhaba, yarın için bir saç kesimi randevusu almak istiyorum',
    'demo.turkishMessage2': 'Tabii! Yarın için uygun saatlerimiz: 10:00, 14:30 ve 16:00. Hangisi size uygun?',
    
    // Footer
    'footer.description': 'Kuaför ve güzellik salonları için yapay zeka destekli WhatsApp randevu asistanı.',
    'footer.product': 'Ürün',
    'footer.features': 'Özellikler',
    'footer.pricing': 'Fiyatlandırma',
    'footer.adminPanel': 'Admin Panel',
    'footer.legal': 'Yasal',
    'footer.privacyPolicy': 'Gizlilik Politikası',
    'footer.termsOfService': 'Kullanım Koşulları',
    'footer.kvkkText': 'KVKK Aydınlatma Metni',
    'footer.copyright': '© 2025 Kuafi.com. Tüm hakları saklıdır.',
    'footer.metaBadge': 'Meta Business Partner',
  },
  en: {
    // Header
    'header.announcement': '📢 TRY 7 DAYS FREE - No credit card required! | Special launch discount: 20% off',
    'nav.features': 'Features',
    'nav.howItWorks': 'How It Works',
    'nav.pricing': 'Pricing',
    'nav.adminPanel': 'Admin Panel',
    'nav.tryFree': 'Try 7 Days Free',
    
    // Hero Section
    'hero.badge.new': 'New',
    'hero.badge.trustedBy': 'Trusted by 500+ barbers',
    'hero.title': 'WhatsApp-Based',
    'hero.titleHighlight': '24/7 Appointment System',
    'hero.subtitle': 'AI-powered WhatsApp appointment assistant for hair salons and beauty parlors. Your customers write, your assistant responds instantly.',
    'hero.testimonial': '"I\'ve been using it for 3 months, my appointments increased by 40% and I never miss an appointment!"',
    'hero.testimonialAuthor': '- Ahmet Barber, Istanbul',
    'hero.cta': 'Try for Free',
    'hero.benefit1': '7 days free trial',
    'hero.benefit2': 'No credit card required',
    'hero.benefit3': 'Meta approved partner',
    
    // WhatsApp Demo
    'demo.assistant': 'Kuafi Assistant',
    'demo.online': 'Online',
    'demo.message1': 'Hello! I\'m Kuafi assistant. How can I help you?',
    'demo.message2': 'Hello, I would like to book a haircut appointment for tomorrow',
    'demo.message3': 'Sure! Available times for tomorrow: 10:00, 14:30 and 16:00. Which one works for you?',
    
    // Features Section
    'features.title': 'Personalized WhatsApp Assistant for You',
    'features.subtitle': 'Separate setup and configuration for each beauty salon',
    'features.smartAppointment.title': 'Smart Appointment Management',
    'features.smartAppointment.feature1': 'Automatic appointment scheduling',
    'features.smartAppointment.feature2': 'Appointment cancellation/rescheduling',
    'features.smartAppointment.feature3': 'Available time suggestions',
    'features.smartAppointment.feature4': 'Reminder messages',
    'features.aiAssistant.title': 'AI Assistant',
    'features.aiAssistant.feature1': 'Natural language understanding',
    'features.aiAssistant.feature2': 'Turkish and English support',
    'features.aiAssistant.feature3': 'Smart suggestions',
    'features.aiAssistant.feature4': '24/7 service',
    'features.security.title': 'Security and Compliance',
    'features.security.feature1': 'Meta approved API',
    'features.security.feature2': 'GDPR compliant',
    'features.security.feature3': 'SSL security',
    'features.security.feature4': 'Data backup',
    
    // Success Metrics Section
    'metrics.title': 'Success Metrics',
    'metrics.subtitle': 'Real results from businesses using Kuafi.com',
    'metrics.bookingIncrease.title': 'Appointment Booking Increase',
    'metrics.bookingIncrease.description': 'Empty appointment slots decrease, your business volume increases',
    'metrics.timeSaving.title': 'Phone Time Savings',
    'metrics.timeSaving.description': 'Time lost answering phone calls decreases',
    'metrics.newCustomers.title': 'New Customer Increase',
    'metrics.newCustomers.description': '24/7 appointment booking capability increases new customer acquisition',
    'metrics.cancellationReduction.title': 'Cancellation Rate Reduction',
    'metrics.cancellationReduction.description': 'Fewer appointment cancellations thanks to automatic reminders',
    'metrics.testimonial': '"After starting to work with Kuafi.com, the time I spent on the phone decreased by 90% and my appointment booking rate increased by 67%. Now I can provide better quality service to my customers."',
    'metrics.testimonialAuthor': 'Ahmet Barber',
    'metrics.testimonialLocation': 'Istanbul, Kadikoy',
    
    // How It Works Section
    'howItWorks.title': 'How It Works?',
    'howItWorks.subtitle': 'Simple in 3 Steps',
    'howItWorks.step1.title': 'Customer Writes',
    'howItWorks.step1.description': 'Your customers easily reach you via WhatsApp.',
    'howItWorks.step2.title': 'Bot Responds',
    'howItWorks.step2.description': 'AI-powered assistant automatically creates appointments.',
    'howItWorks.step3.title': 'Added to Calendar',
    'howItWorks.step3.description': 'Appointment is automatically added to your calendar.',
    
    // Pricing Section
    'pricing.title': 'Pricing Plans',
    'pricing.subtitle': 'Choose the best plan for your business',
    
    // Final CTA Section
    'finalCta.title': 'Ready to Add WhatsApp Assistant to Your Business?',
    'finalCta.subtitle': 'Less work, more appointments. Grow your business with an assistant that responds to your customers 24/7.',
    'finalCta.cta': 'Try 7 Days Free',
    
    // FAQ Section
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Answers to your questions',
    'faq.q1.question': 'Is WhatsApp API difficult to set up?',
    'faq.q1.answer': 'No, WhatsApp API setup with Kuafi is completely done by us. WhatsApp Business API setup and integration is included in our Premium package.',
    'faq.q2.question': 'How long is the trial period?',
    'faq.q2.answer': 'You can try all our features for free for 7 days. No credit card information is required during the trial period.',
    'faq.q3.question': 'Is the bot in Turkish?',
    'faq.q3.answer': 'Yes, our bot has 100% Turkish support and has Turkish language understanding and processing capabilities.',
    'faq.q4.question': 'What does the calendar integrate with?',
    'faq.q4.answer': 'We currently support Google Calendar, Microsoft Outlook and Apple Calendar integrations. We can also provide integration with your custom calendar systems.',
    'faq.q5.question': 'What happens to my old appointments?',
    'faq.q5.answer': 'All appointments in your existing calendar system are preserved. Kuafi works in a way that respects your existing appointments.',
    
    // Admin Features Section
    'adminFeatures.badge': 'NEW',
    'adminFeatures.title': 'Advanced Management Panel',
    'adminFeatures.subtitle': 'Meet the powerful admin panel where you can manage your business from a single point',
    'adminFeatures.appointmentManagement.title': 'Appointment Management',
    'adminFeatures.appointmentManagement.description': 'View, edit and cancel all your appointments. Easily track free hours and busy days.',
    'adminFeatures.customerDatabase.title': 'Customer Database',
    'adminFeatures.customerDatabase.description': 'Manage your customer information from one place. Easily access appointment history, preferences and contact information.',
    'adminFeatures.analytics.title': 'Analytics and Reports',
    'adminFeatures.analytics.description': 'Measure your business performance. Access occupancy rates, cancellation statistics and revenue reports.',
    'adminFeatures.customizable.title': 'Customizable Control Panel',
    'adminFeatures.customizable.description': 'Customize your management panel according to your needs. Highlight the metrics that are important to you.',
    'adminFeatures.customizable.feature1': 'Daily, weekly and monthly appointment views',
    'adminFeatures.customizable.feature2': 'WhatsApp messaging history and statistics',
    'adminFeatures.customizable.feature3': 'Customizable automatic message templates',
    'adminFeatures.customizable.feature4': 'Detailed financial reports and forecasts',
    'adminFeatures.customizable.cta': 'Learn More',
    'adminFeatures.mobile.title': 'Mobile Access',
    'adminFeatures.mobile.description': 'Access your admin panel from anywhere, on any device. Manage your business even on the go with a fully mobile-friendly interface.',
    'adminFeatures.mobile.badge': '100% Mobile Compatible',
    'adminFeatures.mobile.subtitle': 'Perfect experience on all devices',
    'adminFeatures.multiUser.title': 'Multi-User Support',
    'adminFeatures.multiUser.description': 'Define special permissions for different members of your team. You decide who can see and edit what.',
    'adminFeatures.multiUser.roleAccess': 'Role-Based Access',
    'adminFeatures.multiUser.roles': 'Manager, employee and assistant roles',
    
    // Contact Section
    'contact.quickContact': 'Get in Touch Now',
    'contact.title': 'Quick Contact and References',
    'contact.subtitle': 'Turkey\'s leading 500+ businesses automate their appointment systems with Kuafi.com',
    'contact.testimonialsTitle': 'What Our Users Say?',
    'contact.testimonial1': '"After I started using Kuafi.com, my empty appointment hours decreased by 80%. Now I can focus on my customers instead of dealing with phone calls."',
    'contact.testimonial1Author': 'Ahmet Barber',
    'contact.testimonial1Location': 'Istanbul, Kadikoy',
    'contact.testimonial1Duration': 'Using for 4 months',
    'contact.testimonial2': '"Our customers are very happy that they can make appointments 24/7 via WhatsApp. Especially reminder messages significantly reduced cancellation rates."',
    'contact.testimonial2Author': 'Deniz Beauty',
    'contact.testimonial2Location': 'Ankara, Cankaya',
    'contact.testimonial2Duration': 'Using for 6 months',
    'contact.formTitle': 'Contact Us',
    'contact.nameLabel': 'Full Name',
    'contact.namePlaceholder': 'Your Name Surname',
    'contact.phoneLabel': 'Phone Number',
    'contact.phonePlaceholder': '+90 5XX XXX XX XX',
    'contact.emailLabel': 'Email',
    'contact.emailPlaceholder': 'example@domain.com',
    'contact.businessTypeLabel': 'Business Type',
    'contact.businessTypePlaceholder': 'Select',
    'contact.messageLabel': 'Message',
    'contact.messagePlaceholder': 'Your questions or details...',
    'contact.submitButton': 'Send Message',
    'contact.privacyNote': 'Your information is protected under GDPR.',
    'contact.privacyLink': 'Our Privacy Policy',
    'contact.businessOption1': 'Hair Salon / Beauty Parlor',
    'contact.businessOption2': 'SPA / Massage Parlor',
    'contact.businessOption3': 'Dietitian',
    'contact.businessOption4': 'Doctor / Clinic',
    'contact.businessOption5': 'Other',
    
    // Pricing Section
    'pricing.videoTitle': 'Discover Kuafi.com in 45 seconds',
    'pricing.specialOffer': '⏳ Special Offer: 20% Discount - Last Day!',
    'pricing.comparison.features': 'Features',
    'pricing.comparison.competitor1': 'Competitor X',
    'pricing.comparison.competitor2': 'Competitor Y',
    'pricing.comparison.whatsappApi': 'WhatsApp API',
    'pricing.comparison.turkishSupport': 'Turkish Language Support',
    'pricing.comparison.calendarIntegration': 'Calendar Integrations',
    'pricing.comparison.support247': '24/7 Turkish Support',
    'pricing.comparison.adminPanel': 'Advanced Admin Panel',
    
    // Pricing Plans
    'pricing.freePlan.title': '🎉 Free Plan',
    'pricing.freePlan.description': 'Ideal for getting started',
    'pricing.freePlan.price': '$0',
    'pricing.freePlan.period': '/month',
    'pricing.freePlan.cta': 'Start',
    'pricing.freePlan.feature1': '30 day trial',
    'pricing.freePlan.feature2': '100 messages / month',
    'pricing.freePlan.feature3': 'Email support',
    
    'pricing.standardPlan.badge': 'RECOMMENDED',
    'pricing.standardPlan.title': '💼 Standard Plan',
    'pricing.standardPlan.description': 'For small and medium businesses',
    'pricing.standardPlan.originalPrice': '$25',
    'pricing.standardPlan.price': '$20',
    'pricing.standardPlan.period': '/month',
    'pricing.standardPlan.discount': '20% off - limited time!',
    'pricing.standardPlan.cta': 'Get Started Now',
    'pricing.standardPlan.feature1': 'Unlimited messages',
    'pricing.standardPlan.feature2': 'Custom calendar integration',
    'pricing.standardPlan.feature3': 'Brand customizations',
    'pricing.standardPlan.feature4': 'WhatsApp support',
    'pricing.standardPlan.feature5': 'Basic admin panel features',
    'pricing.standardPlan.note': 'WhatsApp message costs ($0.0055/message) are covered by you. For detailed information',
    'pricing.standardPlan.clickHere': 'click here',
    
    'pricing.premiumPlan.title': '👑 Premium Plan',
    'pricing.premiumPlan.description': 'For large businesses and chains',
    'pricing.premiumPlan.originalPrice': '$50',
    'pricing.premiumPlan.price': '$40',
    'pricing.premiumPlan.period': '/month',
    'pricing.premiumPlan.discount': '20% off - limited time!',
    'pricing.premiumPlan.cta': 'Contact Us',
    'pricing.premiumPlan.feature1': 'All features +',
    'pricing.premiumPlan.feature2': 'WhatsApp Business API setup',
    'pricing.premiumPlan.feature3': '24/7 support',
    'pricing.premiumPlan.feature4': 'Priority support',
    'pricing.premiumPlan.feature5': 'First 1000 messages on us! (Value: $50)',
    'pricing.premiumPlan.feature6': 'Advanced admin panel features',
    'pricing.premiumPlan.note': 'In Premium package, WhatsApp message costs are covered by us.',
    
    'pricing.whatsappCosts.title': 'About WhatsApp Message Costs',
    'pricing.whatsappCosts.description': 'WhatsApp message costs are not hidden from you! Meta charges per message for WhatsApp Business API usage.',
    'pricing.whatsappCosts.standardTitle': 'In Standard Package',
    'pricing.whatsappCosts.standardNote': 'WhatsApp message costs ($0.0055/message) are covered by you.',
    'pricing.whatsappCosts.premiumTitle': 'In Premium Package',
    'pricing.whatsappCosts.premiumNote': 'WhatsApp message costs are covered by us + first 1000 messages on us!',
    
    // Demo Section
    'demo.title': 'Live Demo',
    'demo.subtitle': 'Start chatting with the bot with one click and experience Kuafi.com right away.',
    'demo.tryWhatsApp': 'Try on WhatsApp',
    'demo.getDemo': 'I Want a Demo',
    'demo.turkishMessage1': 'Hello, I would like to book a haircut appointment for tomorrow',
    'demo.turkishMessage2': 'Sure! Available times for tomorrow: 10:00, 14:30 and 16:00. Which one works for you?',
    
    // Footer
    'footer.description': 'AI-powered WhatsApp appointment assistant for hair salons and beauty parlors.',
    'footer.product': 'Product',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.adminPanel': 'Admin Panel',
    'footer.legal': 'Legal',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.kvkkText': 'GDPR Information Text',
    'footer.copyright': '© 2025 Kuafi.com. All rights reserved.',
    'footer.metaBadge': 'Meta Business Partner',

    // Legal Pages
    'kvkk.backToHome': 'Back to Home',
    'kvkk.title': 'KVKK Disclosure Text',
    'kvkk.subtitle': 'Disclosure Text Under the Personal Data Protection Law No. 6698',
    'kvkk.lastUpdated': 'Last updated: June 17, 2025',
    'kvkk.dataController.title': '1. Data Controller',
    'kvkk.dataController.description': 'In accordance with the Personal Data Protection Law No. 6698 ("KVKK"), your personal data may be processed by Kuafi Technology Inc. as the data controller within the scope described below.',
    'kvkk.dataController.info': 'Data Controller Information',
    'kvkk.dataController.company': 'Company: Kuafi Technology Inc.',
    'kvkk.dataController.address': 'Address: Maslak, Büyükdere Cad. No:123, Sarıyer/Istanbul',
    'kvkk.dataController.email': 'Email: kvkk@kuafi.com',
    'kvkk.dataController.phone': 'Phone: +90 (555) 123 4567',
    'kvkk.personalData.title': '2. Processed Personal Data',
    'kvkk.personalData.identity': 'Identity Information',
    'kvkk.personalData.identityItem1': 'Name and surname',
    'kvkk.personalData.identityItem2': 'T.C. Identity number (when necessary)',
    'kvkk.personalData.identityItem3': 'Date of birth',
    'kvkk.personalData.contact': 'Contact Information',
    'kvkk.personalData.contactItem1': 'Phone number',
    'kvkk.personalData.contactItem2': 'Email address',
    'kvkk.personalData.contactItem3': 'Business address',
    'kvkk.personalData.transaction': 'Transaction Information',
    'kvkk.personalData.transactionItem1': 'Appointment information',
    'kvkk.personalData.transactionItem2': 'Service usage data',
    'kvkk.personalData.transactionItem3': 'Payment information',
    'kvkk.processingPurposes.title': '3. Personal Data Processing Purposes',
    'kvkk.processingPurposes.primary': 'Primary Purposes',
    'kvkk.processingPurposes.primaryItem1': 'Providing appointment management service',
    'kvkk.processingPurposes.primaryItem2': 'Managing customer relations',
    'kvkk.processingPurposes.primaryItem3': 'Improving service quality',
    'kvkk.processingPurposes.primaryItem4': 'Fulfilling legal obligations',
    'kvkk.processingPurposes.secondary': 'Secondary Purposes',
    'kvkk.processingPurposes.secondaryItem1': 'Service development and improvement',
    'kvkk.processingPurposes.secondaryItem2': 'Statistical analysis',
    'kvkk.processingPurposes.secondaryItem3': 'Information and marketing (with permission)',
    'kvkk.dataSecurity.title': '4. Data Security and Your Rights',
    'kvkk.dataSecurity.security': 'Security Measures',
    'kvkk.dataSecurity.securityDescription': 'We take all technical and administrative measures to ensure the security of your personal data:',
    'kvkk.dataSecurity.securityItem1': 'SSL/TLS encryption',
    'kvkk.dataSecurity.securityItem2': 'Firewalls',
    'kvkk.dataSecurity.securityItem3': 'Access controls',
    'kvkk.dataSecurity.securityItem4': 'Regular security tests',
    'kvkk.dataSecurity.rights': 'Your Rights Under KVKK',
    'kvkk.dataSecurity.rightsItem1': 'Learning whether your personal data is processed',
    'kvkk.dataSecurity.rightsItem2': 'Requesting information about this if your personal data has been processed',
    'kvkk.dataSecurity.rightsItem3': 'Learning the purpose of processing your personal data and whether they are used in accordance with the purpose',
    'kvkk.dataSecurity.rightsItem4': 'Knowing the third parties to whom your personal data is transferred domestically or abroad',
    'kvkk.dataSecurity.rightsItem5': 'Requesting the correction of your personal data if processed incompletely or incorrectly',
    'kvkk.dataSecurity.rightsItem6': 'Requesting the deletion of your personal data under the conditions set forth in Article 7 of KVKK',
    'kvkk.contact.title': '5. Contact',
    'kvkk.contact.description': 'You can contact us for your requests regarding personal data protection:',
    'kvkk.contact.email': 'Email: kvkk@kuafi.com',
    'kvkk.contact.phone': 'Phone: +90 (555) 123 4567',
    'kvkk.contact.address': 'Written application to our company address',

    'privacyPolicy.backToHome': 'Back to Home',
    'privacyPolicy.title': 'Privacy Policy',
    'privacyPolicy.subtitle': 'At Kuafi.com, the security of your personal data is our priority. This policy explains how we collect, use and protect your data.',
    'privacyPolicy.lastUpdated': 'Last updated: June 17, 2025',
    'privacyPolicy.dataCollection.title': '1. Information We Collect',
    'privacyPolicy.dataCollection.personal': 'Personal Information',
    'privacyPolicy.dataCollection.personalItem1': 'kuafiapp@gmail.com',
    'privacyPolicy.dataCollection.personalItem2': '+90 505 007 98 55',
    'privacyPolicy.dataCollection.automatic': 'Automatically Collected Information',
    'privacyPolicy.dataCollection.automaticItem1': 'IP address and device information',
    'privacyPolicy.dataCollection.automaticItem2': 'Browser type and version',
    'privacyPolicy.dataCollection.automaticItem3': 'Page view statistics',
    'privacyPolicy.dataCollection.automaticItem4': 'Service usage data',
    'privacyPolicy.dataCollection.whatsapp': 'WhatsApp Message Data',
    'privacyPolicy.dataCollection.whatsappItem1': 'Customer appointment requests',
    'privacyPolicy.dataCollection.whatsappItem2': 'Message content (only for appointment transactions)',
    'privacyPolicy.dataCollection.whatsappItem3': 'Message timing',
    'privacyPolicy.dataCollection.whatsappItem4': 'Appointment status information',
    'privacyPolicy.dataUsage.title': '2. How We Use Data',
    'privacyPolicy.dataUsage.service': 'Service Provision',
    'privacyPolicy.dataUsage.serviceDescription': 'We use your data to provide our appointment assistant service, manage appointments and communicate with your customers.',
    'privacyPolicy.dataUsage.improvement': 'Service Improvement',
    'privacyPolicy.dataUsage.improvementDescription': 'We analyze anonymous usage data to improve our services, add new features and enhance user experience.',
    'privacyPolicy.dataUsage.communication': 'Communication',
    'privacyPolicy.dataUsage.communicationDescription': 'We communicate with you for important service updates, security notifications and support services.',
    'privacyPolicy.dataUsage.legal': 'Legal Obligations',
    'privacyPolicy.dataUsage.legalDescription': 'We may use your data when necessary to meet legal requirements, prevent fraud and ensure security.',
    'privacyPolicy.dataSharing.title': '3. Data Sharing',
    'privacyPolicy.dataSharing.principle': 'Our Basic Principle',
    'privacyPolicy.dataSharing.principleDescription': 'We never share, sell or rent your personal data to third parties for marketing purposes.',
    'privacyPolicy.dataSharing.limited': 'Limited Sharing Situations',
    'privacyPolicy.dataSharing.limitedItem1': 'Service Providers: WhatsApp API, cloud storage and analytics services',
    'privacyPolicy.dataSharing.limitedItem2': 'Legal Requirements: In case of court order or legal obligation',
    'privacyPolicy.dataSharing.limitedItem3': 'Security: In case of fraud or security threats',
    'privacyPolicy.dataSharing.limitedItem4': 'Business Transfer: In case of company sale or merger (with prior notice)',
    'privacyPolicy.cookies.title': '4. Cookies and Tracking Technologies',
    'privacyPolicy.cookies.types': 'Cookies We Use',
    'privacyPolicy.cookies.necessary': 'Necessary Cookies',
    'privacyPolicy.cookies.necessaryDescription': 'Provides basic functions of the website',
    'privacyPolicy.cookies.analytics': 'Analytics Cookies',
    'privacyPolicy.cookies.analyticsDescription': 'Helps us understand site usage',
    'privacyPolicy.cookies.functional': 'Functional Cookies',
    'privacyPolicy.cookies.functionalDescription': 'Remembers your preferences',
    'privacyPolicy.cookies.marketing': 'Marketing Cookies',
    'privacyPolicy.cookies.marketingDescription': 'Shows relevant content and ads',
    'privacyPolicy.cookies.control': 'Cookie Control',
    'privacyPolicy.cookies.controlDescription': 'You can manage cookie preferences through your browser settings. However, disabling some cookies may affect site functionality.',
    'privacyPolicy.dataSecurity.title': '5. Data Security',
    'privacyPolicy.dataSecurity.measures': 'Security Measures',
    'privacyPolicy.dataSecurity.measuresItem1': 'End-to-end encryption',
    'privacyPolicy.dataSecurity.measuresItem2': 'Regular security audits',
    'privacyPolicy.dataSecurity.measuresItem3': 'Employee training',
    'privacyPolicy.dataSecurity.measuresItem4': 'Secure data centers',
    'privacyPolicy.dataSecurity.measuresItem5': 'Regular backups',
    'privacyPolicy.dataSecurity.breach': 'Data Breach',
    'privacyPolicy.dataSecurity.breachDescription': 'In the unlikely event of a data breach, we will notify you and relevant authorities within 72 hours.',
    'privacyPolicy.rights.title': '6. Your Rights',
    'privacyPolicy.rights.item1': 'Access your personal data',
    'privacyPolicy.rights.item2': 'Correct inaccurate data',
    'privacyPolicy.rights.item3': 'Delete your account and data',
    'privacyPolicy.rights.item4': 'Data portability',
    'privacyPolicy.rights.item5': 'Object to processing',
    'privacyPolicy.rights.item6': 'Withdraw consent',
    'privacyPolicy.rights.exercise': 'To exercise these rights, contact us at privacy@kuafi.com',
    'privacyPolicy.contact.title': '7. Contact',
    'privacyPolicy.contact.description': 'For questions about this privacy policy:',
    'privacyPolicy.contact.email': 'Email: privacy@kuafi.com',
    'privacyPolicy.contact.phone': 'Phone: +90 505 007 98 55',
    'privacyPolicy.contact.address': 'Address: Maslak, Büyükdere Cad. No:123, Sarıyer/Istanbul',

    'terms.backToHome': 'Back to Home',
    'terms.title': 'Terms of Service',
    'terms.subtitle': 'Rules and conditions you must follow when using Kuafi.com services.',
    'terms.lastUpdated': 'Last updated: June 17, 2025',
    'terms.general.title': '1. General Terms',
    'terms.general.description': 'These terms of use determine the rules and conditions you must follow when using Kuafi.com services. By using our services, you are deemed to have accepted these terms.',
    'terms.general.scope': 'Service Scope',
    'terms.general.scopeItem1': 'Appointment management via WhatsApp',
    'terms.general.scopeItem2': 'AI-powered customer communication',
    'terms.general.scopeItem3': 'Calendar integration',
    'terms.general.scopeItem4': 'Business management tools',
    'terms.responsibilities.title': '2. User Responsibilities',
    'terms.responsibilities.account': 'Account Security',
    'terms.responsibilities.accountDescription': 'You are responsible for the security of your account information. If you notice any suspicious activity, contact us immediately.',
    'terms.responsibilities.prohibited': 'Prohibited Uses',
    'terms.responsibilities.prohibitedItem1': 'Sending spam or unwanted messages',
    'terms.responsibilities.prohibitedItem2': 'Illegal or unethical activities',
    'terms.responsibilities.prohibitedItem3': 'System abuse',
    'terms.responsibilities.prohibitedItem4': 'Behavior that violates the rights of others',
    'terms.payment.title': '3. Payment and Cancellation Terms',
    'terms.payment.conditions': 'Payment Terms',
    'terms.payment.conditionsItem1': 'Monthly or annual subscription options',
    'terms.payment.conditionsItem2': 'Auto-renewal feature',
    'terms.payment.conditionsItem3': 'Secure payment infrastructure',
    'terms.payment.conditionsItem4': 'VAT inclusive pricing',
    'terms.payment.cancellation': 'Cancellation and Refund',
    'terms.payment.cancellationItem1': 'Right to refund within 14 days',
    'terms.payment.cancellationItem2': 'Cancel anytime',
    'terms.payment.cancellationItem3': 'Refund for unused period',
    'terms.payment.cancellationItem4': 'Use until end of period after cancellation',
    'terms.liability.title': '4. Disclaimer',
    'terms.liability.description': 'Kuafi.com does not guarantee that its services will work uninterrupted and error-free. It is not responsible for damages that may arise from the service, to the extent permitted by law.',
    'terms.liability.limited': 'Limited Liability',
    'terms.liability.limitedDescription': 'In any case, Kuafi.com\'s liability cannot exceed the service fee you paid in the last 12 months.',
    'terms.liability.force': 'Force Majeure',
    'terms.liability.forceDescription': 'Kuafi.com cannot be held responsible for interruptions and disruptions caused by force majeure such as natural disasters, war, terrorism, epidemic diseases.',
    'terms.contact.title': '5. Contact',
    'terms.contact.description': 'You can contact us for questions about these terms of use:',
    'terms.contact.email': 'Email: legal@kuafi.com',
    'terms.contact.phone': 'Phone: +90 505 007 98 55',
    'terms.contact.address': 'Address: Maslak, Büyükdere Cad. No:123, Sarıyer/Istanbul',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
    document.documentElement.lang = lang
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 